version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/backend
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app_start.sh
      runas: ubuntu

